import React from 'react';
import type { WeatherData } from '../../types/weather';
import './WeatherReport.css';

interface WeatherReportProps {
    data: WeatherData | null;
}

const WeatherReport: React.FC<WeatherReportProps> = ({ data }) => {
    if (!data) return null;

    const { name, main, weather, wind, sys, dt } = data;
    const weatherMain = weather[0];

    const formatDate = (timestamp: number) => {
        return new Date(timestamp * 1000).toLocaleString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    const formatTime = (timestamp: number) => {
        return new Date(timestamp * 1000).toLocaleTimeString('en-US', {
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    const generateSummary = () => {
        const condition = weatherMain.description;
        const temp = Math.round(main.temp);
        const humidity = main.humidity;
        return `The weather in ${name} today is ${condition} with a temperature of ${temp}°C and ${humidity}% humidity. Wind is blowing at ${wind.speed} m/s.`;
    };

    const downloadReport = () => {
        const reportText = `
WEATHER REPORT: ${name.toUpperCase()}
Date: ${formatDate(dt)}
---------------------------------------------
Location: ${name}, ${sys.country}
Condition: ${weatherMain.main} (${weatherMain.description})
Current Temp: ${Math.round(main.temp)}°C
Feels Like: ${Math.round(main.feels_like)}°C
Min Temp: ${Math.round(main.temp_min)}°C
Max Temp: ${Math.round(main.temp_max)}°C

Humidity: ${main.humidity}%
Wind Speed: ${wind.speed} m/s
Pressure: ${main.pressure} hPa

Sunrise: ${formatTime(sys.sunrise)}
Sunset: ${formatTime(sys.sunset)}
---------------------------------------------
Summary: ${generateSummary()}
---------------------------------------------
Generated by SkyCast Weather Hub
    `.trim();

        const blob = new Blob([reportText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Weather_Report_${name}_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="weather-report-section">
            <div className="report-card">
                <div className="report-header">
                    <h3>Detailed Weather Report</h3>
                    <button className="download-btn" onClick={downloadReport}>
                        📥 Download Report
                    </button>
                </div>

                <div className="report-grid">
                    <div className="report-item">
                        <span className="label">Location</span>
                        <span className="value">{name}, {sys.country}</span>
                    </div>
                    <div className="report-item">
                        <span className="label">Date & Time</span>
                        <span className="value">{formatDate(dt)}</span>
                    </div>
                    <div className="report-item">
                        <span className="label">Temperature</span>
                        <span className="value">{Math.round(main.temp)}°C (Feels like {Math.round(main.feels_like)}°C)</span>
                    </div>
                    <div className="report-item">
                        <span className="label">Min/Max Temp</span>
                        <span className="value">{Math.round(main.temp_min)}°C / {Math.round(main.temp_max)}°C</span>
                    </div>
                    <div className="report-item">
                        <span className="label">Condition</span>
                        <span className="value" style={{ textTransform: 'capitalize' }}>{weatherMain.description}</span>
                    </div>
                    <div className="report-item">
                        <span className="label">Humidity</span>
                        <span className="value">{main.humidity}%</span>
                    </div>
                    <div className="report-item">
                        <span className="label">Wind Speed</span>
                        <span className="value">{wind.speed} m/s</span>
                    </div>
                    <div className="report-item">
                        <span className="label">Sunrise / Sunset</span>
                        <span className="value">{formatTime(sys.sunrise)} / {formatTime(sys.sunset)}</span>
                    </div>
                </div>

                <div className="report-summary">
                    <h4>Weather Summary</h4>
                    <p>"{generateSummary()}"</p>
                </div>
            </div>
        </div>
    );
};

export default WeatherReport;
